trigger: none

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-tests.yml
  parameters:
    ServiceDirectory: storage
    BuildInParallel: false
    TimeoutInMinutes: 360
    Location: canadacentral
    Clouds: AzureCloud_Preview
    TestSetupSteps:
    - template: /sdk/storage/tests-install-azurite.yml
