parameters:
- name: AdditionalPlatforms
  type: object
  default: []
- name: PreSteps
  type: object
  default: []
- name: PostSteps
  type: object
  default: []
- name: EnvVars
  type: object
  default: {}
- name: MaxParallel
  type: number
  default: 0
- name: BuildInParallel
  type: boolean
  default: true
- name: TimeoutInMinutes
  type: number
  default: 60
- name: Location
  type: string
  default: ''
- name: TestCanary
  type: boolean
  default: false
- name: ServiceDirectory
  type: string
  default: not-specified
- name: TestSetupSteps
  type: stepList
  default: []
- name: Clouds
  type: string
  default: 'AzureCloud'
- name: ResourceGroupLocationCanary
  type: string
  default: "centraluseuap"

stages:
  - template: ../stages/clouds/clouds.yml
    parameters:
      AdditionalParameters:
        PreSteps: ${{ parameters.PreSteps }}
        PostSteps: ${{ parameters.PostSteps }}
        EnvVars: ${{ parameters.EnvVars }}
        MaxParallel: ${{ parameters.MaxParallel }}
        BuildInParallel: ${{ parameters.BuildInParallel }}
        TimeoutInMinutes: ${{ parameters.TimeoutInMinutes }}
        Location: ${{ parameters.Location }}
        ServiceDirectory: ${{ parameters.ServiceDirectory }}
        TestSetupSteps: ${{ parameters.TestSetupSteps }}
      Platforms: 
      - DisplayName: "Test on Linux"
        OSVmImage: "ubuntu-18.04"
        TestTargetFramework: netcoreapp2.1
        PreSteps:
          - template: /eng/common/pipelines/templates/steps/bypass-local-dns.yml
      - DisplayName: "Test on Windows for NetCoreApp"
        OSVmImage: "windows-2019"
        TestTargetFramework: netcoreapp2.1
      - DisplayName: "Test on Windows for NetCoreApp with UseProjectReferenceToAzureClients=true"
        OSVmImage: "windows-2019"
        TestTargetFramework: netcoreapp2.1
        AdditionalTestArguments: /p:UseProjectReferenceToAzureClients=true
      - DisplayName: "Test on Windows for .Net Framework"
        OSVmImage: "windows-2019"
        TestTargetFramework: net461
      - DisplayName: "Test on Windows for .Net Framework with UseProjectReferenceToAzureClients=true"
        OSVmImage: "windows-2019"
        TestTargetFramework: net461
        AdditionalTestArguments: /p:UseProjectReferenceToAzureClients=true
      - DisplayName: "Test on MacOS"
        OSVmImage: "macOS-10.15"
        TestTargetFramework: netcoreapp2.1
      - ${{ if eq(parameters.TestCanary, 'true') }}:          
        - DisplayName: "Test on Windows for NetCoreApp - Canary region"
          OSVmImage: "windows-2019"
          TestTargetFramework: netcoreapp2.1
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview)            
          Location: ${{ parameters.ResourceGroupLocationCanary }}
      - DisplayName: "Record on Windows for NetCoreApp"
        OSVmImage: "windows-2019"
        TestMode: Record
        TestTargetFramework: netcoreapp2.1
        PostSteps:
          - task: CopyFiles@2
            displayName: "Copy Test Recordings"
            inputs:
              sourceFolder: '$(Build.SourcesDirectory)'
              contents: 'sdk/${{ parameters.ServiceDirectory }}/**/SessionRecords/**/*.json'
              targetFolder: '$(Build.ArtifactStagingDirectory)/SessionRecords'
          - task: PublishBuildArtifacts@1
            displayName: "Publish Test Recordings"
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)/SessionRecords'
              artifactName: SessionRecords
      - ${{ parameters.AdditionalPlatforms }}
