parameters:
- name: Clouds
  type: string
  default: ''
- name: AdditionalParameters
  type: object
  default: {}
- name: Location
  type: string
- name: Platforms
  type: object
  default: {}
- name: CloudConfig
  type: object
  default: {}

stages:
- stage: FOOBAR
  dependsOn: []
  jobs:
  - template: ../jobs/archetype-sdk-tests-jobs.yml
    parameters:
      Platforms:
        ${{ each platform in parameters.Platforms }}:
          ${{ if contains(coalesce(platform.value.SupportedClouds, parameters.Clouds), 'AzureCloud') }}:
            ${{ insert }}: ${{ platform }}
      CloudConfig:
        SubscriptionConfiguration: ${{ cloud.value }}
        Location: ${{ coalesce(parameters.Location, cloud.value.Location) }}
      ${{ each param in parameters.AdditionalParameters }}:
        ${{ param.key }}: ${{ param.value }}
- ${{ each cloud in parameters.CloudConfig }}:
  - ${{ if contains(parameters.Clouds, cloud.key) }}:
    - stage: ${{ cloud.key }}
      dependsOn: []
      jobs:
      - template: ../jobs/archetype-sdk-tests-jobs.yml
        parameters:
          Platforms:
            ${{ each platform in parameters.Platforms }}:
              ${{ if contains(coalesce(platform.value.SupportedClouds, parameters.Clouds), cloud.key) }}:
                ${{ insert }}: ${{ platform }}
          CloudConfig:
            SubscriptionConfiguration: ${{ cloud.value }}
            Location: ${{ coalesce(parameters.Location, cloud.value.Location) }}
          ${{ each param in parameters.AdditionalParameters }}:
            ${{ param.key }}: ${{ param.value }}
