parameters:
- name: Clouds
  type: string
  default: ''
- name: AdditionalParameters
  type: object
  default: {}
- name: Location
  type: string
- name: Platforms
  type: object
  default: {}
# - name: CloudConfig
#   type: object
#   default: {}
- name: CloudConfig
  type: object
  default:
    AzureCloud_Public:
      SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-test)
    AzureCloud_Preview:
      SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview-test)
    AzureCloud_Canary:
      SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview-test)
      Location: 'eastus2euap'
    AzureUsGovCloud:
      SubscriptionConfiguration: $(sub-config-gov-test-resources-test)
    AzureChinaCloud:
      SubscriptionConfiguration: $(sub-config-cn-test-resources-test)

stages:
  - stage: Test
    jobs:
    - template: ../jobs/archetype-sdk-tests-jobs.yml
      parameters:
        Platforms:
          Linux_NetCore:
            DisplayName: "Test on Linux"
            OSVmImage: "ubuntu-18.04"
            TestTargetFramework: netcoreapp2.1
        CloudConfig:
          AzureCloud_Public:
            SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-test)
  - ${{ each cloud in parameters.CloudConfig }}:
    - ${{ if contains(parameters.Clouds, cloud.key) }}:
      - stage: ${{ cloud.key }}
        dependsOn: []
        jobs:
        - template: ../jobs/archetype-sdk-tests-jobs.yml
          parameters:
            Platforms:
              MacOS:
                Test: foo
  #            ${{ each platform in parameters.Platforms }}:
  #              ${{ if contains(coalesce(platform.value.SupportedClouds, parameters.Clouds), cloud.key) }}:
  #                ${{ insert }}: ${{ platform }}
            CloudConfig:
              SubscriptionConfiguration: ${{ cloud.value }}
              Location: ${{ coalesce(parameters.Location, cloud.value.Location) }}
            ${{ each param in parameters.AdditionalParameters }}:
              ${{ param.key }}: ${{ param.value }}
