parameters:
- name: AdditionalPlatforms
  type: object
  default: {}
- name: Clouds
  type: string
  default: 'AzureCloud'
- name: PreSteps
  type: object
  default: []
- name: PostSteps
  type: object
  default: []
- name: EnvVars
  type: object
  default: {}
- name: MaxParallel
  type: number
  default: 0
- name: BuildInParallel
  type: boolean
  default: true
- name: TimeoutInMinutes
  type: number
  default: 60
- name: Location
  type: string
  default: ''
- name: ServiceDirectory
  type: string
  default: not-specified
- name: TestSetupSteps
  type: stepList
  default: []
- name: CloudConfig
  type: object
  default:
    AzureCloud_Public:
      SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-test)
    AzureCloud_Preview:
      SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview-test)
    AzureCloud_Canary:
      SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview-test)
      Location: 'eastus2euap'
    AzureUsGovCloud:
      SubscriptionConfiguration: $(sub-config-gov-test-resources-test)
    AzureChinaCloud:
      SubscriptionConfiguration: $(sub-config-cn-test-resources-test)
- name: Platforms
  type: object
  default:
    Platforms:
      Linux_NetCore:
        DisplayName: "Test on Linux"
        OSVmImage: "ubuntu-18.04"
        TestTargetFramework: netcoreapp2.1
        #        PreSteps:
        #  - template: /eng/common/pipelines/templates/steps/bypass-local-dns.yml
            #      Windows_NetCore:
            #        DisplayName: "Test on Windows for NetCoreApp"
            #        OSVmImage: "windows-2019"
            #        TestTargetFramework: netcoreapp2.1
            #      Windows_NetCore_ProjectRefAzureClients:
            #        DisplayName: "Test on Windows for NetCoreApp with UseProjectReferenceToAzureClients=true"
            #        OSVmImage: "windows-2019"
            #        TestTargetFramework: netcoreapp2.1
            #        AdditionalTestArguments: /p:UseProjectReferenceToAzureClients=true
            #      Windows_NetFramework:
            #        DisplayName: "Test on Windows for .Net Framework"
            #        OSVmImage: "windows-2019"
            #        TestTargetFramework: net461
            #      Windows_NetFramework_ProjectRefAzureClients:
            #        DisplayName: "Test on Windows for .Net Framework with UseProjectReferenceToAzureClients=true"
            #        OSVmImage: "windows-2019"
            #        TestTargetFramework: net461
            #        AdditionalTestArguments: /p:UseProjectReferenceToAzureClients=true
            #      MacOS:
            #        DisplayName: "Test on MacOS"
            #        OSVmImage: "macOS-10.15"
            #        TestTargetFramework: netcoreapp2.1
            #        SupportedClouds: 'AzureCloud'
            #      Windows_NetCore_Record:
            #        DisplayName: "Record on Windows for NetCoreApp"
            #        OSVmImage: "windows-2019"
            #        TestMode: Record
            #        TestTargetFramework: netcoreapp2.1
            #        AdditionalTestArguments: /p:AutoUpdateSessionRecords=true
            #        PostSteps:
            #          - task: CopyFiles@2
            #            displayName: "Copy Test Recordings"
            #            inputs:
            #              sourceFolder: '$(Build.SourcesDirectory)'
            #              contents: 'sdk/${{ parameters.ServiceDirectory }}/**/SessionRecords/**/*.json'
            #              targetFolder: '$(Build.ArtifactStagingDirectory)/SessionRecords'
            #          - task: PublishBuildArtifacts@1
            #            displayName: "Publish Test Recordings"
            #            inputs:
            #              pathToPublish: '$(Build.ArtifactStagingDirectory)/SessionRecords'
            #              artifactName: SessionRecords
            #        SupportedClouds: 'AzureCloud'

stages:
  #- stage: Test
  #  jobs:
  #  - template: ../jobs/archetype-sdk-tests-jobs.yml
  #    parameters:
  #      Platforms:
  #        Linux_NetCore:
  #          DisplayName: "Test on Linux"
  #          OSVmImage: "ubuntu-18.04"
  #          TestTargetFramework: netcoreapp2.1
  #      CloudConfig:
  #        AzureCloud_Public:
  #          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-test)
- ${{ each cloud in parameters.CloudConfig }}:
  - ${{ if contains(parameters.Clouds, cloud.key) }}:
    - stage: ${{ cloud.key }}
      dependsOn: []
      jobs:
      - template: ../jobs/archetype-sdk-tests-jobs.yml
        parameters:
          Platforms:
            ${{ each platform in parameters.Platforms }}:
              ${{ if contains(coalesce(platform.value.SupportedClouds, parameters.Clouds), cloud.key) }}:
                ${{ platform.key }}: ${{ platform.value }}
          CloudConfig:
            SubscriptionConfiguration: ${{ cloud.value }}
            Location: ${{ coalesce(parameters.Location, cloud.value.Location) }}
          ${{ each param in parameters.AdditionalParameters }}:
            ${{ param.key }}: ${{ param.value }}

  ### - template: ./archetype-sdk-tests-clouds.yml
  ###   parameters:
  ###     Clouds: ${{ parameters.Clouds }}
  ###     Location: ${{ parameters.Location }}
  ###     ### CloudConfig:
  ###     ###   AzureCloud_Public:
  ###     ###     SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-test)
  ###     Platforms:
  ###       MacOS:
  ###         DisplayName: "Test on MacOS"
  ###         OSVmImage: "macOS-10.15"
  ###         TestTargetFramework: netcoreapp2.1
  ###         SupportedClouds: 'AzureCloud'
  ###       # ${{ insert }}: ${{ parameters.Platforms }}
  ###       # ${{ insert }}: ${{ parameters.AdditionalPlatforms }}
  ###     AdditionalParameters:
  ###       PreSteps: ${{ parameters.PreSteps }}
  ###       PostSteps: ${{ parameters.PostSteps }}
  ###       EnvVars: ${{ parameters.EnvVars }}
  ###       MaxParallel: ${{ parameters.MaxParallel }}
  ###       BuildInParallel: ${{ parameters.BuildInParallel }}
  ###       TimeoutInMinutes: ${{ parameters.TimeoutInMinutes }}
  ###       ServiceDirectory: ${{ parameters.ServiceDirectory }}
  ###       TestSetupSteps: ${{ parameters.TestSetupSteps }}
