parameters:
- name: Clouds
  type: string
  default: ''
- name: Platforms
  type: object
  default: []
- name: AdditionalParameters
  type: object
  default: []
- name: Location
  type: string
- name: CloudConfig
  type: object
  default:
    AzureCloud_Public:
      SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-test)
    AzureCloud_Preview:
      SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview-test)
    AzureCloud_Canary:
      SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview-test)
      Location: 'eastus2euap'
    AzureUsGovCloud:
      SubscriptionConfiguration: $(sub-config-gov-test-resources-test)
    AzureChinaCloud:
      SubscriptionConfiguration: $(sub-config-cn-test-resources-test)

stages:
  - ${{ each cloud in parameters.CloudConfig }}:
    - ${{ if or(contains(variables['LiveTestClouds'], cloud.key), contains(parameters.Clouds, cloud.key)) }}:
      - stage: ${{ cloud.key }}
        dependsOn: []
        jobs:
        - template: ../jobs/archetype-sdk-tests-platforms.yml
          parameters:
            AdditionalParameters: ${{ parameters.AdditionalParameters }}
            Platforms:
              ${{ each platform in parameters.Platforms }}:
                ${{ if contains(coalesce(platform.value.SupportedClouds, parameters.Clouds), cloud.key) }}:
                  ${{ platform.key }}: ${{ platform.value }}
            CloudConfig:
              SubscriptionConfiguration: ${{ cloud.value.SubscriptionConfiguration }}
              Location: ${{ coalesce(parameters.Location, cloud.value.Location) }}
